# Generated by Django 6.0.5 on 2026-06-02 17:46

import direccion.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='Formatos: .jpg, .jpeg, .png', null=True, upload_to=direccion.models.investigado_photo_path, verbose_name='Foto')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('entrada_investigacion', models.TextField(blank=True, help_text='Breve resumen del porqué está siendo investigado', null=True, verbose_name='Entrada a investigación')),
                ('cedula', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[VEJPGvejpg]-?\\d{5,10}$', 'Formato: V-12345678')], verbose_name='Cédula')),
                ('rif', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[VEJPGvejpg]-?\\d{5,10}-\\d$', 'Formato: V-12345678-0')], verbose_name='RIF')),
                ('partida_nacimiento', models.CharField(blank=True, help_text='Tomo, folio o datos de acta', max_length=255, null=True, verbose_name='Partida de nacimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Investigado',
                'verbose_name_plural': 'Personas a Investigar',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='Formatos: .jpg, .jpeg, .png', null=True, upload_to=direccion.models.personal_photo_path, verbose_name='Foto')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('cedula', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[VEJPGvejpg]-?\\d{5,10}$', 'Formato: V-12345678')], verbose_name='Cédula')),
                ('telefonos', models.TextField(blank=True, help_text='Ingrese uno o varios números', null=True, verbose_name='Teléfonos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal de la Dirección',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoInvestigado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Formatos: PDF, Word (.doc, .docx), imágenes', upload_to=direccion.models.investigado_document_path, verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('IMAGEN', 'Imagen'), ('OTRO', 'Otro')], editable=False, max_length=10, verbose_name='Tipo')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('investigado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='direccion.investigado', verbose_name='Investigado')),
            ],
            options={
                'verbose_name': 'Documento de Evidencia',
                'verbose_name_plural': 'Documentos de Evidencias',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Formatos: PDF, Word (.doc, .docx), imágenes', upload_to=direccion.models.personal_document_path, verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('IMAGEN', 'Imagen'), ('OTRO', 'Otro')], editable=False, max_length=10, verbose_name='Tipo')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='direccion.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Documento del Personal',
                'verbose_name_plural': 'Documentos del Personal',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ANALISTA', 'Analista'), ('ADMINISTRATIVO', 'Administrativo')], default='ADMINISTRATIVO', max_length=20, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
