# Generated by Django 6.0.5 on 2026-06-02 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Nombre de usuario')),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('ACTUALIZAR', 'Actualización'), ('ELIMINAR', 'Eliminación'), ('TOGGLE', 'Activar/Desactivar'), ('LOGIN', 'Inicio de sesión'), ('EXPORTAR', 'Exportación')], max_length=20, verbose_name='Acción')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('objeto_repr', models.CharField(blank=True, max_length=255, verbose_name='Representación')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
