# Generated by Django 6.0.5 on 2026-06-03 14:00

import direccion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Formatos: PDF, Word (.doc, .docx), imágenes', upload_to=direccion.models.direccion_document_path, verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('IMAGEN', 'Imagen'), ('OTRO', 'Otro')], editable=False, max_length=10, verbose_name='Tipo')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
            ],
            options={
                'verbose_name': 'Documento de la Dirección',
                'verbose_name_plural': 'Documentos de la Dirección',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AlterModelOptions(
            name='investigado',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Caso', 'verbose_name_plural': 'Casos'},
        ),
        migrations.AlterField(
            model_name='documentoinvestigado',
            name='investigado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='direccion.investigado', verbose_name='Caso'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='entrada_investigacion',
            field=models.TextField(blank=True, help_text='Breve resumen del caso', null=True, verbose_name='Entrada a investigación'),
        ),
    ]
