# Generated by Django 6.0.5 on 2026-06-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0003_documentodireccion_alter_investigado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentodireccion',
            name='categoria',
            field=models.CharField(choices=[('REGLAMENTO', 'Reglamento'), ('OFICIO', 'Oficio'), ('INFORME', 'Informe'), ('CIRCULAR', 'Circular'), ('RESOLUCION', 'Resolución'), ('ACTA', 'Acta'), ('CONVENIO', 'Convenio'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Categoría'),
        ),
    ]
