# Generated by Django 6.0.5 on 2026-06-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0004_documentodireccion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentodireccion',
            name='categoria',
            field=models.CharField(choices=[('LEYES', 'Leyes'), ('DOCUMENTOS', 'Documentos'), ('MEMO', 'Memo'), ('ACTAS', 'Actas')], default='DOCUMENTOS', max_length=20, verbose_name='Categoría'),
        ),
    ]
