# Generated by Django 6.0.5 on 2026-06-03 18:54

import direccion.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0005_alter_documentodireccion_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del caso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_apertura', models.DateField(blank=True, null=True, verbose_name='Fecha de apertura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='documentodireccion',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento de la DirecciÃ³n', 'verbose_name_plural': 'Documentos de la DirecciÃ³n'},
        ),
        migrations.AlterModelOptions(
            name='investigado',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Persona Investigada', 'verbose_name_plural': 'Personas Investigadas'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personal de la DirecciÃ³n'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('ACTUALIZAR', 'Actualización'), ('ELIMINAR', 'Eliminación'), ('RESTAURAR', 'Restauración'), ('TOGGLE', 'Activar/Desactivar'), ('LOGIN', 'Inicio de sesión'), ('EXPORTAR', 'Exportación')], max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='documentodireccion',
            name='archivo',
            field=models.FileField(help_text='Formatos: PDF, Word (.doc, .docx), imÃ¡genes', upload_to=direccion.models.direccion_document_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentodireccion',
            name='categoria',
            field=models.CharField(choices=[('LEYES', 'Leyes'), ('DOCUMENTOS', 'Documentos'), ('MEMO', 'Memo'), ('ACTAS', 'Actas')], default='DOCUMENTOS', max_length=20, verbose_name='CategorÃ\xada'),
        ),
        migrations.AlterField(
            model_name='documentodireccion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='documentoinvestigado',
            name='archivo',
            field=models.FileField(help_text='Formatos: PDF, Word (.doc, .docx), imÃ¡genes', upload_to=direccion.models.investigado_document_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentoinvestigado',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='documentoinvestigado',
            name='investigado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='direccion.investigado', verbose_name='Persona Investigada'),
        ),
        migrations.AlterField(
            model_name='documentopersonal',
            name='archivo',
            field=models.FileField(help_text='Formatos: PDF, Word (.doc, .docx), imÃ¡genes', upload_to=direccion.models.personal_document_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentopersonal',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[VEJPGvejpg]-?\\d{5,10}$', 'Formato: V-12345678')], verbose_name='CÃ©dula'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='entrada_investigacion',
            field=models.TextField(blank=True, help_text='Breve resumen del caso', null=True, verbose_name='Entrada a investigaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cedula',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[VEJPGvejpg]-?\\d{5,10}$', 'Formato: V-12345678')], verbose_name='CÃ©dula'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefonos',
            field=models.TextField(blank=True, help_text='Ingrese uno o varios nÃºmeros', null=True, verbose_name='TelÃ©fonos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TelÃ©fono'),
        ),
        migrations.AddField(
            model_name='investigado',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigados', to='direccion.caso', verbose_name='Caso'),
        ),
    ]
