# Generated by Django 6.0.5 on 2026-06-04 15:49

import direccion.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0006_caso_alter_documentodireccion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentodireccion',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento de la Dirección', 'verbose_name_plural': 'Documentos de la Dirección'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personal de la Dirección'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('ACTUALIZAR', 'Actualización'), ('ELIMINAR', 'Eliminación'), ('RESTAURAR', 'Restauración'), ('TOGGLE', 'Activar/Desactivar'), ('LOGIN', 'Inicio de sesión'), ('EXPORTAR', 'Exportación'), ('BACKUP', 'Respaldo')], max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='documentodireccion',
            name='archivo',
            field=models.FileField(help_text='Formatos: PDF, Word (.doc, .docx), imágenes', upload_to=direccion.models.direccion_document_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentodireccion',
            name='categoria',
            field=models.CharField(choices=[('LEYES', 'Leyes'), ('DOCUMENTOS', 'Documentos'), ('MEMO', 'Memo'), ('ACTAS', 'Actas')], default='DOCUMENTOS', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='documentodireccion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='documentoinvestigado',
            name='archivo',
            field=models.FileField(help_text='Formatos: PDF, Word (.doc, .docx), imágenes', upload_to=direccion.models.investigado_document_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentoinvestigado',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='documentopersonal',
            name='archivo',
            field=models.FileField(help_text='Formatos: PDF, Word (.doc, .docx), imágenes', upload_to=direccion.models.personal_document_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentopersonal',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[VEJPGvejpg]-?\\d{5,10}$', 'Formato: V-12345678')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='entrada_investigacion',
            field=models.TextField(blank=True, help_text='Breve resumen del caso', null=True, verbose_name='Entrada a investigación'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cedula',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[VEJPGvejpg]-?\\d{5,10}$', 'Formato: V-12345678')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefonos',
            field=models.TextField(blank=True, help_text='Ingrese uno o varios números', null=True, verbose_name='Teléfonos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas Pendientes',
                'ordering': ['completada', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
