# Generated by Django 6.0.5 on 2026-06-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0008_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='prioridad',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=10, verbose_name='Prioridad'),
        ),
    ]
