# Generated by Django 6.0.5 on 2026-06-04 18:23

import direccion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0009_tarea_prioridad_ticketsoporte_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Formatos: PDF, Word (.doc, .docx), imágenes', upload_to=direccion.models.caso_document_path, verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('IMAGEN', 'Imagen'), ('OTRO', 'Otro')], editable=False, max_length=10, verbose_name='Tipo')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='direccion.caso', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Documento del Caso',
                'verbose_name_plural': 'Documentos del Caso',
                'ordering': ['-fecha_subida'],
            },
            bases=(direccion.models.TipoDocumentoMixin, models.Model),
        ),
    ]
