# Generated by Django 6.0.5 on 2026-06-04 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0010_documentocaso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('estado', 'Estado'), ('prioridad', 'Prioridad'), ('asignado_a', 'Asignado a')], max_length=20, verbose_name='Campo')),
                ('valor_anterior', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor nuevo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='direccion.ticketsoporte', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_cambios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cambio en Ticket',
                'verbose_name_plural': 'Historial de Tickets',
                'ordering': ['-fecha'],
            },
        ),
    ]
