# Generated by Django 6.0.5 on 2026-06-04 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0011_tickethistorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido del informe')),
                ('archivo', models.FileField(blank=True, help_text='Opcional: PDF, Word, imagen...', null=True, upload_to='informes/archivos/', verbose_name='Archivo adjunto')),
                ('fecha', models.DateField(verbose_name='Fecha del informe')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Informe Diario',
                'verbose_name_plural': 'Informes Diarios',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
