# Generated by Django 6.0.5 on 2026-06-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0012_informediario'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='rango',
            field=models.CharField(blank=True, choices=[('', '--- Sin rango ---'), ('DISTINGUIDO', 'Distinguido'), ('CABO_SEGUNDO', 'Cabo Segundo'), ('CABO_PRIMERO', 'Cabo Primero'), ('SARGENTO_SEGUNDO', 'Sargento Segundo'), ('SARGENTO_PRIMERO', 'Sargento Primero'), ('SARGENTO_MAYOR', 'Sargento Mayor'), ('OFICIAL', 'Oficial'), ('OFICIAL_JEFE', 'Oficial Jefe'), ('OFICIAL_MAYOR', 'Oficial Mayor'), ('COMISIONADO', 'Comisionado'), ('INSPECTOR', 'Inspector'), ('SUB_TENIENTE', 'Sub-Teniente'), ('SEGUNDO_TENIENTE', 'Segundo Teniente'), ('PRIMER_TENIENTE', 'Primer Teniente'), ('CAPITAN', 'Capitán'), ('MAYOR', 'Mayor'), ('TENIENTE_CORONEL', 'Teniente Coronel'), ('CORONEL', 'Coronel'), ('GENERAL', 'General')], default='', help_text='Solo para personal militar o policial', max_length=30, verbose_name='Rango'),
        ),
    ]
