# Generated by Django 6.0.5 on 2026-06-10 16:20

import direccion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0013_personal_rango'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del bien')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('foto', models.ImageField(blank=True, help_text='Formatos: .jpg, .jpeg, .png', null=True, upload_to=direccion.models.bien_photo_path, verbose_name='Foto')),
                ('categoria', models.CharField(choices=[('VEHICULO', 'Vehículo'), ('INMUEBLE', 'Inmueble'), ('EQUIPO', 'Equipo'), ('MUEBLE', 'Mueble'), ('ARMAMENTO', 'Armamento'), ('COMUNICACIONES', 'Comunicaciones'), ('INFORMATICA', 'Informática'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Categoría')),
                ('codigo_inventario', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de inventario')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo_bien', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('OBSOLETO', 'Obsoleto')], default='BUENO', max_length=20, verbose_name='Estado')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor (Bs.)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('ANALISTA', 'Analista'), ('ADMINISTRATIVO', 'Administrativo')], default='ADMINISTRATIVO', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='DocumentoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Formatos: PDF, Word (.doc, .docx), imágenes', upload_to=direccion.models.bien_document_path, verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('IMAGEN', 'Imagen'), ('OTRO', 'Otro')], editable=False, max_length=10, verbose_name='Tipo')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='direccion.bien', verbose_name='Bien')),
            ],
            options={
                'verbose_name': 'Documento del Bien',
                'verbose_name_plural': 'Documentos de Bienes',
                'ordering': ['-fecha_subida'],
            },
            bases=(direccion.models.TipoDocumentoMixin, models.Model),
        ),
    ]
