# Generated by Django 6.0.5 on 2026-06-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0014_bien_alter_userprofile_rol_documentobien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='rango',
        ),
        migrations.AddField(
            model_name='bien',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes', to='direccion.caso', verbose_name='Caso'),
        ),
        migrations.AddField(
            model_name='personal',
            name='contacto_emergencia',
            field=models.TextField(blank=True, help_text='Nombre, parentesco y teléfono', null=True, verbose_name='Contacto de Emergencia'),
        ),
        migrations.AddField(
            model_name='personal',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección de domicilio', null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='personal',
            name='grado',
            field=models.CharField(blank=True, default='', help_text='Grado profesional / jerárquico', max_length=100, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('ACTUALIZAR', 'Actualización'), ('ELIMINAR', 'Eliminación'), ('RESTAURAR', 'Restauración'), ('TOGGLE', 'Activar/Desactivar'), ('LOGIN', 'Inicio de sesión'), ('EXPORTAR', 'Exportación'), ('BACKUP', 'Respaldo')], db_index=True, max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='modelo',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='categoria',
            field=models.CharField(choices=[('VEHICULO', 'Vehículo'), ('INMUEBLE', 'Inmueble'), ('EQUIPO', 'Equipo'), ('MUEBLE', 'Mueble'), ('ARMAMENTO', 'Armamento'), ('COMUNICACIONES', 'Comunicaciones'), ('INFORMATICA', 'Informática'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='estado',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('OBSOLETO', 'Obsoleto')], db_index=True, default='BUENO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nombre del caso'),
        ),
        migrations.AlterField(
            model_name='documentobien',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='documentobien',
            name='tipo',
            field=models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('IMAGEN', 'Imagen'), ('OTRO', 'Otro')], db_index=True, editable=False, max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='documentocaso',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='documentocaso',
            name='tipo',
            field=models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('IMAGEN', 'Imagen'), ('OTRO', 'Otro')], db_index=True, editable=False, max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='documentodireccion',
            name='categoria',
            field=models.CharField(choices=[('LEYES', 'Leyes'), ('DOCUMENTOS', 'Documentos'), ('MEMO', 'Memo'), ('ACTAS', 'Actas')], db_index=True, default='DOCUMENTOS', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='documentodireccion',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='documentodireccion',
            name='tipo',
            field=models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('IMAGEN', 'Imagen'), ('OTRO', 'Otro')], db_index=True, editable=False, max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='documentoinvestigado',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='documentoinvestigado',
            name='tipo',
            field=models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('IMAGEN', 'Imagen'), ('OTRO', 'Otro')], db_index=True, editable=False, max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='documentopersonal',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='documentopersonal',
            name='tipo',
            field=models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('IMAGEN', 'Imagen'), ('OTRO', 'Otro')], db_index=True, editable=False, max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='fecha',
            field=models.DateField(db_index=True, verbose_name='Fecha del informe'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='apellidos',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='investigado',
            name='nombres',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Leída'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='apellidos',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombres',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Completada'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], db_index=True, default='ABIERTO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='prioridad',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], db_index=True, default='MEDIO', max_length=10, verbose_name='Prioridad'),
        ),
    ]
