# -*- coding: utf-8 -*-
# Generated by Django 6.0.5 on 2026-06-12 19:00
from django.db import migrations, models
import django.db.models.deletion
import direccion.models


class Migration(migrations.Migration):

    dependencies = [
        ("direccion", "0015_remove_personal_rango_bien_caso_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarpetaUsuario",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("orden", models.IntegerField(default=0, verbose_name="Orden")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="carpetas_usuario", to="auth.user", verbose_name="Usuario")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="subcarpetas", to="direccion.CarpetaUsuario", verbose_name="Carpeta padre")),
            ],
            options={
                "verbose_name": "Carpeta de Usuario",
                "verbose_name_plural": "Carpetas de Usuarios",
                "ordering": ["orden", "nombre"],
                "unique_together": {("usuario", "nombre", "parent")},
            },
        ),
        migrations.CreateModel(
            name="DocumentoUsuario",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archivo", models.FileField(upload_to='documentos_usuario/', verbose_name="Archivo")),
                ("tipo", models.CharField(choices=[("PDF", "PDF"), ("WORD", "Word"), ("IMAGEN", "Imagen"), ("OTRO", "Otro")], db_index=True, editable=False, max_length=10, verbose_name="Tipo")),
                ("descripcion", models.CharField(blank=True, max_length=255, null=True, verbose_name="Descripcion")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Fecha de subida")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documentos_usuario", to="auth.user", verbose_name="Usuario")),
                ("carpeta", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="documentos", to="direccion.CarpetaUsuario", verbose_name="Carpeta")),
            ],
            options={
                "verbose_name": "Documento del Usuario",
                "verbose_name_plural": "Documentos de Usuarios",
                "ordering": ["-fecha_subida"],
            },
        ),
    ]
