# Generated by Django 6.0.5 on 2026-06-13 14:52

import direccion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0016_documentousuario_carpetausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpetausuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentousuario',
            name='archivo',
            field=models.FileField(help_text='PDF, Word, imagenes', upload_to='documentos_usuario/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentousuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CarpetaBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='direccion.carpetabien', verbose_name='Carpeta padre')),
            ],
            options={
                'verbose_name': 'Carpeta de Bien',
                'verbose_name_plural': 'Carpetas de Bienes',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CarpetaDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('categoria', models.CharField(blank=True, max_length=20, null=True, verbose_name='Categoria')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='direccion.carpetadireccion', verbose_name='Carpeta padre')),
            ],
            options={
                'verbose_name': 'Carpeta de Documento',
                'verbose_name_plural': 'Carpetas de Documentos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='documentodireccion',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='direccion.carpetadireccion', verbose_name='Carpeta'),
        ),
    ]
