# Generated by Django 4.x on 2026-06-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0017_alter_carpetausuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='correo',
            field=models.EmailField(blank=True, help_text='Correo electronico institucional o personal', max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
    ]
