# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0018_add_correo_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='correo',
            field=models.EmailField(blank=True, help_text='Correo electronico institucional o personal', max_length=254, null=True, unique=True, verbose_name='Correo Electronico'),
        ),
    ]
