# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0019_alter_personal_correo_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes', to='direccion.carpetabien', verbose_name='Carpeta'),
        ),
    ]
