# Generated by Django 6.0.5 on 2026-06-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0023_remove_documentousuario_carpeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='correo',
            field=models.CharField(blank=True, help_text='Correo electrónico institucional o personal', max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
