# Generated by Django 6.0.5 on 2026-06-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0024_alter_personal_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentodireccion',
            name='categoria',
            field=models.CharField(choices=[('LEYES', 'Leyes'), ('DOCUMENTOS', 'Documentos'), ('MEMO', 'Formato de Memos'), ('RECURSOS', 'Recursos CIM5')], db_index=True, default='DOCUMENTOS', max_length=20, verbose_name='Categoría'),
        ),
    ]
