# Generated by Django 6.0.5 on 2026-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0025_alter_documentodireccion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='categoria',
            field=models.CharField(choices=[('GENERAL', 'General'), ('INVESTIGACION', 'Investigación'), ('DOCUMENTACION', 'Documentación'), ('SOPORTE', 'Soporte Técnico'), ('ADMINISTRACION', 'Administración'), ('REUNION', 'Reuniones'), ('OTRO', 'Otro')], db_index=True, default='GENERAL', max_length=20, verbose_name='Categoría'),
        ),
    ]
