# Generated by Django 6.0.5 on 2026-06-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0026_tarea_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpetabien',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
