# ============================================================
# Permisos del Sistema - Direccion General
# Cada permiso representa una accion concreta sobre un modulo.
# ============================================================

# --- Permisos individuales ---
DASHBOARD_VER = 'dashboard_ver'

PERSONAL_VER = 'personal_ver'
PERSONAL_CREAR = 'personal_crear'
PERSONAL_EDITAR = 'personal_editar'
PERSONAL_ELIMINAR = 'personal_eliminar'
PERSONAL_DOCUMENTOS_AGREGAR = 'personal_documentos_agregar'
PERSONAL_DOCUMENTOS_ELIMINAR = 'personal_documentos_eliminar'

CASOS_VER = 'casos_ver'
CASOS_CREAR = 'casos_crear'
CASOS_EDITAR = 'casos_editar'
CASOS_ELIMINAR = 'casos_eliminar'
CASOS_DOCUMENTOS_AGREGAR = 'casos_documentos_agregar'
CASOS_DOCUMENTOS_ELIMINAR = 'casos_documentos_eliminar'

INVESTIGADOS_VER = 'investigados_ver'
INVESTIGADOS_CREAR = 'investigados_crear'
INVESTIGADOS_EDITAR = 'investigados_editar'
INVESTIGADOS_ELIMINAR = 'investigados_eliminar'
INVESTIGADOS_DOCUMENTOS_AGREGAR = 'investigados_documentos_agregar'
INVESTIGADOS_DOCUMENTOS_ELIMINAR = 'investigados_documentos_eliminar'

DOCUMENTOS_DIRECCION_VER = 'documentos_direccion_ver'
DOCUMENTOS_DIRECCION_SUBIR = 'documentos_direccion_subir'

# --- Permisos de Carpetas de Bienes ---
BIENES_CARPETAS_CREAR = "bienes_carpetas_crear"
BIENES_CARPETAS_RENOMBRAR = "bienes_carpetas_renombrar"
BIENES_CARPETAS_ELIMINAR = "bienes_carpetas_eliminar"
# --- Permisos de Carpetas de Documentos ---

DOCUMENTOS_DIRECCION_CARPETAS_RENOMBRAR = "documentos_direccion_carpetas_renombrar"
DOCUMENTOS_DIRECCION_CARPETAS_ELIMINAR = "documentos_direccion_carpetas_eliminar"
DOCUMENTOS_DIRECCION_EDITAR = 'documentos_direccion_editar'
DOCUMENTOS_DIRECCION_ELIMINAR = 'documentos_direccion_eliminar'
DOCUMENTOS_DIRECCION_CARPETAS_CREAR = 'documentos_direccion_carpetas_crear'

INFORMES_VER = 'informes_ver'
INFORMES_CREAR = 'informes_crear'
INFORMES_ELIMINAR = 'informes_eliminar'
INFORMES_PREVIEW = 'informes_preview'
INFORMES_DESCARGAR = 'informes_descargar'

TICKETS_VER = 'tickets_ver'
TICKETS_CREAR = 'tickets_crear'
TICKETS_ASIGNAR = 'tickets_asignar'
TICKETS_RESOLVER = 'tickets_resolver'

TAREAS_VER = 'tareas_ver'
TAREAS_CREAR = 'tareas_crear'
TAREAS_COMPLETAR = 'tareas_completar'
TAREAS_ELIMINAR = 'tareas_eliminar'

USUARIOS_VER = 'usuarios_ver'
USUARIOS_CREAR = 'usuarios_crear'
USUARIOS_EDITAR = 'usuarios_editar'
USUARIOS_ELIMINAR = 'usuarios_eliminar'
USUARIOS_TOGGLE = 'usuarios_toggle'

AUDITORIA_VER = 'auditoria_ver'
AUDITORIA_EXPORTAR_EXCEL = 'auditoria_exportar_excel'
AUDITORIA_EXPORTAR_PDF = 'auditoria_exportar_pdf'

BACKUP_DESCARGAR = 'backup_descargar'
BACKUP_RESTAURAR = 'backup_restaurar'

REPORTES_VER = 'reportes_ver'
BIENES_VER = 'bienes_ver'
BIENES_CREAR = 'bienes_crear'
BIENES_EDITAR = 'bienes_editar'
BIENES_ELIMINAR = 'bienes_eliminar'
BIENES_DOCUMENTOS_AGREGAR = 'bienes_documentos_agregar'
BIENES_DOCUMENTOS_ELIMINAR = 'bienes_documentos_eliminar'
NOTIFICACIONES_VER = 'notificaciones_ver'

EXPORTAR_PERSONAL_EXCEL = 'exportar_personal_excel'
EXPORTAR_PERSONAL_PDF = 'exportar_personal_pdf'
EXPORTAR_INVESTIGADOS_EXCEL = 'exportar_investigados_excel'
EXPORTAR_INVESTIGADOS_PDF = 'exportar_investigados_pdf'


TODOS_LOS_PERMISOS = frozenset({
    DASHBOARD_VER,
    PERSONAL_VER, PERSONAL_CREAR, PERSONAL_EDITAR, PERSONAL_ELIMINAR,
    PERSONAL_DOCUMENTOS_AGREGAR, PERSONAL_DOCUMENTOS_ELIMINAR,
    CASOS_VER, CASOS_CREAR, CASOS_EDITAR, CASOS_ELIMINAR,
    CASOS_DOCUMENTOS_AGREGAR, CASOS_DOCUMENTOS_ELIMINAR,
    INVESTIGADOS_VER, INVESTIGADOS_CREAR, INVESTIGADOS_EDITAR, INVESTIGADOS_ELIMINAR,
    INVESTIGADOS_DOCUMENTOS_AGREGAR, INVESTIGADOS_DOCUMENTOS_ELIMINAR,
    DOCUMENTOS_DIRECCION_VER, DOCUMENTOS_DIRECCION_SUBIR, DOCUMENTOS_DIRECCION_EDITAR, DOCUMENTOS_DIRECCION_ELIMINAR, DOCUMENTOS_DIRECCION_CARPETAS_CREAR, DOCUMENTOS_DIRECCION_CARPETAS_RENOMBRAR, DOCUMENTOS_DIRECCION_CARPETAS_ELIMINAR,
    INFORMES_VER, INFORMES_CREAR, INFORMES_ELIMINAR, INFORMES_PREVIEW, INFORMES_DESCARGAR,
    TICKETS_VER, TICKETS_CREAR, TICKETS_ASIGNAR, TICKETS_RESOLVER,
    TAREAS_VER, TAREAS_CREAR, TAREAS_COMPLETAR, TAREAS_ELIMINAR,
    USUARIOS_VER, USUARIOS_CREAR, USUARIOS_EDITAR, USUARIOS_ELIMINAR, USUARIOS_TOGGLE,
    AUDITORIA_VER, AUDITORIA_EXPORTAR_EXCEL, AUDITORIA_EXPORTAR_PDF,
    BACKUP_DESCARGAR, BACKUP_RESTAURAR,
    REPORTES_VER, BIENES_VER, BIENES_CREAR, BIENES_EDITAR, BIENES_ELIMINAR,
    BIENES_DOCUMENTOS_AGREGAR, BIENES_DOCUMENTOS_ELIMINAR,
    BIENES_CARPETAS_CREAR, BIENES_CARPETAS_RENOMBRAR, BIENES_CARPETAS_ELIMINAR,
    NOTIFICACIONES_VER,
    EXPORTAR_PERSONAL_EXCEL, EXPORTAR_PERSONAL_PDF,
    EXPORTAR_INVESTIGADOS_EXCEL, EXPORTAR_INVESTIGADOS_PDF,
})


ROLE_PERMISSIONS = {
    'ADMINISTRADOR': TODOS_LOS_PERMISOS,

    'SUPERVISOR': frozenset({
        DASHBOARD_VER,
        PERSONAL_VER, PERSONAL_CREAR, PERSONAL_EDITAR,
        PERSONAL_DOCUMENTOS_AGREGAR, PERSONAL_DOCUMENTOS_ELIMINAR,
        CASOS_VER, CASOS_CREAR, CASOS_EDITAR,
        CASOS_DOCUMENTOS_AGREGAR, CASOS_DOCUMENTOS_ELIMINAR,
        INVESTIGADOS_VER, INVESTIGADOS_CREAR, INVESTIGADOS_EDITAR,
        INVESTIGADOS_DOCUMENTOS_AGREGAR, INVESTIGADOS_DOCUMENTOS_ELIMINAR,
        DOCUMENTOS_DIRECCION_VER, DOCUMENTOS_DIRECCION_SUBIR, DOCUMENTOS_DIRECCION_EDITAR,
        DOCUMENTOS_DIRECCION_CARPETAS_CREAR, DOCUMENTOS_DIRECCION_CARPETAS_RENOMBRAR, DOCUMENTOS_DIRECCION_CARPETAS_ELIMINAR,
        INFORMES_VER, INFORMES_CREAR, INFORMES_PREVIEW, INFORMES_DESCARGAR,
        TICKETS_VER, TICKETS_CREAR, TICKETS_ASIGNAR, TICKETS_RESOLVER,
        TAREAS_VER, TAREAS_CREAR, TAREAS_COMPLETAR,
        REPORTES_VER, BIENES_VER, BIENES_CREAR, BIENES_EDITAR, BIENES_DOCUMENTOS_AGREGAR,
        NOTIFICACIONES_VER,
        EXPORTAR_PERSONAL_EXCEL, EXPORTAR_PERSONAL_PDF,
        EXPORTAR_INVESTIGADOS_EXCEL, EXPORTAR_INVESTIGADOS_PDF,
    }),

    'ADMINISTRATIVO': frozenset({
        DASHBOARD_VER,
        PERSONAL_VER, PERSONAL_CREAR, PERSONAL_EDITAR, PERSONAL_DOCUMENTOS_AGREGAR,
        CASOS_VER, CASOS_CREAR, CASOS_DOCUMENTOS_AGREGAR,
        INVESTIGADOS_VER, INVESTIGADOS_CREAR,
        INVESTIGADOS_DOCUMENTOS_AGREGAR,
        DOCUMENTOS_DIRECCION_VER, DOCUMENTOS_DIRECCION_SUBIR, DOCUMENTOS_DIRECCION_EDITAR,
        DOCUMENTOS_DIRECCION_CARPETAS_CREAR, DOCUMENTOS_DIRECCION_CARPETAS_RENOMBRAR, DOCUMENTOS_DIRECCION_CARPETAS_ELIMINAR,
        INFORMES_VER, INFORMES_PREVIEW, INFORMES_DESCARGAR,
        TICKETS_VER, TICKETS_CREAR,
        TAREAS_VER, TAREAS_CREAR, TAREAS_COMPLETAR,
        REPORTES_VER, BIENES_VER,
        NOTIFICACIONES_VER,
        EXPORTAR_PERSONAL_EXCEL, EXPORTAR_PERSONAL_PDF,
        EXPORTAR_INVESTIGADOS_EXCEL, EXPORTAR_INVESTIGADOS_PDF,
    }),

    'ANALISTA': frozenset({
        DASHBOARD_VER,
        PERSONAL_VER, PERSONAL_CREAR, PERSONAL_EDITAR, PERSONAL_ELIMINAR,
        DOCUMENTOS_DIRECCION_VER,
        INFORMES_VER, INFORMES_CREAR, INFORMES_PREVIEW, INFORMES_DESCARGAR,
        TICKETS_VER, TICKETS_CREAR,
        TAREAS_VER, TAREAS_CREAR, TAREAS_COMPLETAR,
        NOTIFICACIONES_VER,
    }),
}


def permisos_para_rol(rol):
    return ROLE_PERMISSIONS.get(rol, frozenset())


def tiene_permiso(rol, permiso):
    return permiso in permisos_para_rol(rol)


def verificar_permiso_acceso(usuario, permisos):
    """Verifica si un usuario tiene acceso basado en permisos granulares.

    Retorna True si:
    - El usuario es superuser (is_superuser=True), O
    - El usuario tiene al menos uno de los permisos requeridos via su perfil.

    Retorna False si el usuario no tiene perfil, ocurre un error,
    o no tiene ninguno de los permisos solicitados.
    """
    if usuario.is_superuser:
        return True
    try:
        profile = usuario.profile
        for permiso in permisos:
            if profile.tiene_permiso(permiso):
                return True
    except Exception:
        pass
    return False
